/**
 * NSW District/LGA Codes
 * Source: Property Sales Data File (District Codes and Names) PDF
 * https://valuation.property.nsw.gov.au
 */

export const districtCodes = {
  "001": "Albury City",
  "002": "Armidale Regional",
  "004": "Ballina",
  "005": "Balranald",
  "007": "Bathurst Regional",
  "008": "Bayside",
  "010": "Bega Valley",
  "012": "Bellingen",
  "018": "Blacktown",
  "042": "Bland",
  "043": "Blayney",
  "050": "Blue Mountains",
  "051": "Bogan",
  "052": "Bombala",
  "054": "Boorowa",
  "061": "Bourke",
  "065": "Brewarrina",
  "066": "Broken Hill",
  "070": "Burwood",
  "074": "Byron",
  "081": "Cabonne",
  "082": "Camden",
  "083": "Campbelltown",
  "084": "Canada Bay",
  "085": "Canterbury-Bankstown",
  "087": "Carrathool",
  "088": "Central Coast",
  "090": "Central Darling",
  "092": "Cessnock",
  "097": "City of Sydney",
  "098": "Clarence Valley",
  "100": "Cobar",
  "101": "Coffs Harbour",
  "102": "Coolamon",
  "103": "Coonamble",
  "109": "Cowra",
  "116": "Cumberland",
  "117": "Dubbo Regional",
  "118": "Dungog",
  "123": "Edward River",
  "124": "Eurobodalla",
  "137": "Fairfield",
  "139": "Federation",
  "143": "Forbes",
  "144": "Georges River",
  "148": "Gilgandra",
  "149": "Glen Innes Severn",
  "150": "Goulburn Mulwaree",
  "151": "Greater Hume",
  "152": "Griffith",
  "157": "Gunnedah",
  "158": "Gwydir",
  "159": "Hawkesbury",
  "164": "Hay",
  "171": "Hilltops",
  "187": "Hornsby",
  "188": "Hunter's Hill",
  "192": "Inner West",
  "199": "Inverell",
  "207": "Junee",
  "209": "Kempsey",
  "210": "Kiama",
  "214": "Ku-ring-gai / The Hills",  // Blacktown area too based on the data
  "216": "Kyogle",
  "217": "Lachlan",
  "218": "Lake Macquarie",
  "219": "Lane Cove",
  "220": "Leeton",
  "222": "Lismore",
  "223": "Lithgow",
  "224": "Liverpool",
  "226": "Liverpool Plains",
  "230": "Lockhart",
  "231": "Maitland",
  "232": "Mid-Coast",
  "234": "Mid-Western Regional",
  "236": "Moree Plains",
  "238": "Mosman",
  "239": "Murray River",
  "240": "Murrumbidgee",
  "243": "Muswellbrook",
  "244": "Nambucca",
  "247": "Narrabri",
  "250": "Narrandera",
  "251": "Narromine",
  "253": "Newcastle",
  "254": "North Sydney",
  "255": "Northern Beaches",
  "257": "Oberon",
  "258": "Orange",
  "259": "Parkes",
  "260": "Parramatta",
  "261": "Penrith",
  "262": "Port Macquarie-Hastings",
  "263": "Port Stephens",
  "264": "Queanbeyan-Palerang Regional",
  "265": "Randwick",
  "266": "Richmond Valley",
  "267": "Ryde",
  "268": "Shellharbour",
  "269": "Shoalhaven",
  "270": "Singleton",
  "271": "Snowy Monaro Regional",
  "272": "Snowy Valleys",
  "273": "Strathfield",
  "274": "Sutherland",
  "275": "Tamworth Regional",
  "276": "Temora",
  "300": "Tenterfield",
  "301": "The Hills Shire",
  "302": "Tweed",
  "303": "Upper Hunter",
  "511": "Upper Lachlan",
  "526": "Uralla",
  "528": "Wagga Wagga",
  "529": "Walcha",
  "537": "Walgett",
  "538": "Warren",
  "560": "Warrumbungle",
  "575": "Waverly",
  "608": "Weddin",
  "620": "Wentworth",
  "656": "Willoughby",
  "666": "Wingecarribee",
  "708": "Wollondilly",
  "722": "Wollongong",
  "762": "Woollahra",
  "777": "Yass Valley"
};

export const zoneCodes = {
  // Residential zones
  "R1": { description: "General Residential", category: "Residential" },
  "R2": { description: "Low Density Residential", category: "Residential" },
  "R3": { description: "Medium Density Residential", category: "Residential" },
  "R4": { description: "High Density Residential", category: "Residential" },
  "R5": { description: "Large Lot Residential", category: "Residential" },
  
  // Business zones
  "B1": { description: "Neighbourhood Centre", category: "Commercial" },
  "B2": { description: "Local Centre", category: "Commercial" },
  "B3": { description: "Commercial Core", category: "Commercial" },
  "B4": { description: "Mixed Use", category: "Commercial" },
  "B5": { description: "Business Development", category: "Commercial" },
  "B6": { description: "Enterprise Corridor", category: "Commercial" },
  "B7": { description: "Business Park", category: "Commercial" },
  "B8": { description: "Metropolitan Centre", category: "Commercial" },
  
  // Industrial zones
  "IN1": { description: "General Industrial", category: "Industrial" },
  "IN2": { description: "Light Industrial", category: "Industrial" },
  "IN3": { description: "Heavy Industrial", category: "Industrial" },
  "IN4": { description: "Working Waterfront", category: "Industrial" },
  
  // Special Purpose zones
  "SP1": { description: "Special Activities", category: "Special Purpose" },
  "SP2": { description: "Infrastructure", category: "Special Purpose" },
  "SP3": { description: "Tourist", category: "Special Purpose" },
  
  // Recreation zones
  "RE1": { description: "Public Recreation", category: "Recreation" },
  "RE2": { description: "Private Recreation", category: "Recreation" },
  
  // Environment zones
  "E1": { description: "National Parks and Nature Reserves", category: "Environment" },
  "E2": { description: "Environmental Conservation", category: "Environment" },
  "E3": { description: "Environmental Management", category: "Environment" },
  "E4": { description: "Environmental Living", category: "Environment" },
  
  // Rural zones
  "RU1": { description: "Primary Production", category: "Rural" },
  "RU2": { description: "Rural Landscape", category: "Rural" },
  "RU3": { description: "Forestry", category: "Rural" },
  "RU4": { description: "Primary Production Small Lots", category: "Rural" },
  "RU5": { description: "Village", category: "Rural" },
  "RU6": { description: "Transition", category: "Rural" },
  
  // Waterway zones
  "W1": { description: "Natural Waterways", category: "Waterway" },
  "W2": { description: "Recreational Waterways", category: "Waterway" },
  "W3": { description: "Working Waterways", category: "Waterway" }
};

export const propertyTypes = {
  "R": "Residence",
  "C": "Commercial",
  "I": "Industrial",
  "V": "Vacant Land",
  "F": "Farm/Rural",
  "S": "Strata",
  "M": "Mixed Use"
};

export default { districtCodes, zoneCodes, propertyTypes };
